name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: 'ubuntu-latest'
          swift: '6.0'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    # https://github.com/swift-actions/setup-swift/pull/684
    - uses: swift-actions/setup-swift@736b146b8f26e7a66cbe3a89bc8d413ac0ea536e
      with:
        swift-version: ${{ matrix.swift }}
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libcairo2-dev
    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew update && brew install pkg-config cairo freetype2
    - name: Build
      run: swift build
    - name: Test
      run: swift test
