name: Docs

on:
  push:
    branches:
    - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Pages
      uses: actions/configure-pages@v5
    - name: Set up Swift
    # https://github.com/swift-actions/setup-swift/pull/684
      uses: swift-actions/setup-swift@736b146b8f26e7a66cbe3a89bc8d413ac0ea536e
      with:
        swift-version: '6.0'
    - name: Generate Docs
      uses: fwcd/swift-docc-action@v1
      with:
        target: StaticMap
        output: ./public
        transform-for-static-hosting: 'true'
        disable-indexing: 'true'
        hosting-base-path: swift-static-map
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs

    steps:
    - name: Deploy Docs
      id: deployment
      uses: actions/deploy-pages@v4
